name: Bilingual Docs Sync Check

on:
  push:
    paths:
      - '**.md'
      - 'tools/check_bilingual_sync.py'
  pull_request:
    paths:
      - '**.md'
      - 'tools/check_bilingual_sync.py'

jobs:
  check-bilingual-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Run bilingual sync check
        run: |
          python libra-demos-core/tools/check_bilingual_sync.py
