name: Codecov Coverage
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Run Go tests with coverage
        run: |
          cd blockchain
          go test -coverprofile=coverage.out ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./blockchain/coverage.out
