name: Commitlint
on:
  pull_request:
    types: [opened, synchronize, edited]
jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          npm install --global @commitlint/{config-conventional,cli}
      - name: Lint commits
        run: |
          git log origin/main..HEAD --pretty=format:%s | xargs -I {} npx commitlint --from={} --to=HEAD
