name: Stylelint
on:
  pull_request:
    paths:
      - 'frontend/**/*.css'
jobs:
  stylelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          cd frontend
          npm install
      - name: Run stylelint
        run: |
          npx stylelint "frontend/**/*.css"
